# Generated by Django 4.1.5 on 2023-01-05 17:32

import creator.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=16)),
                ('set_symbol', models.CharField(blank=True, max_length=16, verbose_name='Set Symbol to Use')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.JSONField(verbose_name='Front Face Data')),
                ('front_art', models.ImageField(blank=True, null=True, upload_to=creator.models.CardImagePathRename('front_art'), verbose_name='Front Face Art')),
                ('front_image', models.ImageField(blank=True, null=True, upload_to=creator.models.CardImagePathRename('front_image'), verbose_name='Front Face Image')),
                ('back', models.JSONField(blank=True, null=True, verbose_name='Back Face Data')),
                ('back_art', models.ImageField(blank=True, null=True, upload_to=creator.models.CardImagePathRename('back_art'), verbose_name='Back Face Art')),
                ('back_image', models.ImageField(blank=True, null=True, upload_to=creator.models.CardImagePathRename('back_image'), verbose_name='Back Face Image')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='creator.set')),
            ],
            options={
                'ordering': ['front__text__title__text'],
            },
        ),
    ]
